FROM windowsservercore

RUN powershell.exe -Command \
    $ErrorActionPreference = 'Stop'; \
    wget https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe -OutFile c:\python-3.5.1.exe ; \
    Start-Process c:\python-3.5.1.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ; \
    Remove-Item c:\python-3.5.1.exe -Force
    
RUN pip install requests
RUN pip install slackclient

RUN powershell -Command \
    mkdir c:\stock-bot ; \
    Invoke-WebRequest -Method Get -Uri "https://raw.githubusercontent.com/neilpeterson/slack-stock-bot/master/slack-stock-ticker.py" -OutFile c:\stock-bot\slack-stock-ticker.py

ENTRYPOINT python /stock-bot/slack-stock-ticker.py